import {nanoid} from 'nanoid'

let straipsniai = [ // 2 žingsnis - sukuriamas duomenų failas
    {theme: '', id: nanoid(), img:'https://cdn.pixabay.com/photo/2014/02/27/16/10/flowers-276014__340.jpg', title:'Gamtoje gera', p1: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat animi libero nobis pariatur labore, modi nulla eligendi reiciendis officiis distinctio!', p2: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Eaque consequatur odio earum voluptatem voluptates enim ea eligendi optio odit dolor obcaecati, nulla ipsum voluptatum debitis, corrupti reiciendis perspiciatis numquam nihil accusantium et deleniti. Ex consequuntur libero tempora debitis soluta quis.', p3: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Soluta in, a repellat possimus nam voluptatem ducimus.'},
    {theme: '', id: nanoid(), img:'https://cdn.pixabay.com/photo/2014/02/27/16/10/flowers-276014__340.jpg', title:'Gamtoje visiem gera', p1: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat animi libero nobis pariatur labore, modi nulla eligendi reiciendis officiis distinctio!', p2: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Eaque consequatur odio earum voluptatem voluptates enim ea eligendi optio odit dolor obcaecati, nulla ipsum voluptatum debitis, corrupti reiciendis perspiciatis numquam nihil accusantium et deleniti. Ex consequuntur libero tempora debitis soluta quis.', p3: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Soluta in, a repellat possimus nam voluptatem ducimus.'},
    {theme: '', id: nanoid(), img:'https://cdn.pixabay.com/photo/2014/02/27/16/10/flowers-276014__340.jpg', title:'Gamtoje negera', p1: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat animi libero nobis pariatur labore, modi nulla eligendi reiciendis officiis distinctio!', p2: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Eaque consequatur odio earum voluptatem voluptates enim ea eligendi optio odit dolor obcaecati, nulla ipsum voluptatum debitis, corrupti reiciendis perspiciatis numquam nihil accusantium et deleniti. Ex consequuntur libero tempora debitis soluta quis.', p3: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Soluta in, a repellat possimus nam voluptatem ducimus.'},
    {theme: '', id: nanoid(), img:'https://cdn.pixabay.com/photo/2014/02/27/16/10/flowers-276014__340.jpg', title:'Gamtoje kaip ir kitur', p1: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat animi libero nobis pariatur labore, modi nulla eligendi reiciendis officiis distinctio!', p2: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Eaque consequatur odio earum voluptatem voluptates enim ea eligendi optio odit dolor obcaecati, nulla ipsum voluptatum debitis, corrupti reiciendis perspiciatis numquam nihil accusantium et deleniti. Ex consequuntur libero tempora debitis soluta quis.', p3: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Soluta in, a repellat possimus nam voluptatem ducimus.'},
    {theme: '', id: nanoid(), img:'https://cdn.pixabay.com/photo/2014/02/27/16/10/flowers-276014__340.jpg', title:'Gamtoje kaip gamtoje', p1: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat animi libero nobis pariatur labore, modi nulla eligendi reiciendis officiis distinctio!', p2: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Eaque consequatur odio earum voluptatem voluptates enim ea eligendi optio odit dolor obcaecati, nulla ipsum voluptatum debitis, corrupti reiciendis perspiciatis numquam nihil accusantium et deleniti. Ex consequuntur libero tempora debitis soluta quis.', p3: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Soluta in, a repellat possimus nam voluptatem ducimus.'},
    {theme: '', id: nanoid(), img:'https://cdn.pixabay.com/photo/2014/02/27/16/10/flowers-276014__340.jpg', title:'Gamtoje medžiai auga', p1: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat animi libero nobis pariatur labore, modi nulla eligendi reiciendis officiis distinctio!', p2: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Eaque consequatur odio earum voluptatem voluptates enim ea eligendi optio odit dolor obcaecati, nulla ipsum voluptatum debitis, corrupti reiciendis perspiciatis numquam nihil accusantium et deleniti. Ex consequuntur libero tempora debitis soluta quis.', p3: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Soluta in, a repellat possimus nam voluptatem ducimus.'},
    {theme: '', id: nanoid(), img:'https://cdn.pixabay.com/photo/2014/02/27/16/10/flowers-276014__340.jpg', title:'Tiesiog gamtoje', p1: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat animi libero nobis pariatur labore, modi nulla eligendi reiciendis officiis distinctio!', p2: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Eaque consequatur odio earum voluptatem voluptates enim ea eligendi optio odit dolor obcaecati, nulla ipsum voluptatum debitis, corrupti reiciendis perspiciatis numquam nihil accusantium et deleniti. Ex consequuntur libero tempora debitis soluta quis.', p3: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Soluta in, a repellat possimus nam voluptatem ducimus.'}
]

export default straipsniai